ctrl:
  feat_ext: true
  learn: true
  train_data: all
  dataset_path: '../fsd18kdataset/FSDnoisy18k/'
extract:
  audio_len_s: 2
  eps: 2.220446049250313e-16
  fmax: 22050
  fmin: 0
  fs: 44100
  hop_length_samples: 882
  load_mode: varup
  log: true
  mono: true
  n_fft: 2048
  n_mels: 96
  normalize_audio: true
  patch_hop: 50
  patch_len: 100
  spectrogram_type: power
  win_length_samples: 1764
learn:
  batch_size: 32
  lr: 0.001
  n_classes: 20
  n_epochs: 160
  optim: Adam
  patience: 15
  val_split: 0.15
loss:
  l_loss: 1.9
  m_loss: 0.6
  q_loss: 0.7
  reed_beta: 0.3
  type: CCE
recognizer:
  aggregate: gmean
suffix:
  in: _mel
  out: _label
paths:
  
  pretrained: './pretrained_model.pth'
  checkpoint: './checkpoint.pth'

  train_csv: '../fsd18kdataset/FSDnoisy18k.meta/train.csv'
  test_csv: '../fsd18kdataset/FSDnoisy18k.meta/test.csv'

  test_audio_input: '../fsd18kdataset/FSDnoisy18k.audio_test'
  train_audio_input: '../fsd18kdataset/FSDnoisy18k.audio_train'

  train_feature_extracted: '../features/audio_train_varup2'
  test_feature_extracted: '../features/audio_test_varup2'
  